# Generated by Django 2.2.6 on 2019-11-01 23:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID')),
                ('acompañamiento', models.CharField(choices=[('PalitosQueso', 'PalitosQueso'), ('PalitosAjo', 'PalitosAjo'), 
                ('PalitosCanela', 'PalitosCanela')], max_length=50, null=True)),
                ('cantidad_acompañamiento', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True)),
                ('cantidad_pizza', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')],max_length=50, null=True)),
                ('fecha', models.DateTimeField(auto_now=True, null=True)),
                ('hora', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('n_boleta', models.IntegerField(default=2)),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('precio_final', models.IntegerField(default=45)),
                ('tamaño', models.CharField(choices=[('Individual', 'Individual'), ('Mediana', 'Mediana'), ('Grande', 'Grande'), 
                ('XL', 'XL')], max_length=50, null=True)),
                ('tipo_pizza', models.CharField(choices=[('SuperPeperonni', 'SuperPeperonni'), ('CarnesMix', 'CarnesMix'), 
                ('Italiana', 'Italiana'), ('Española', 'Española'), ('Napolitana', 'Napolitana'), ('Vegetariana', 'Vegetariana'), 
                ('Hawaiana', 'Hawaiana')], max_length=50, null=True)),
            ],
        ),
    ]
