# Generated by Django 2.2.6 on 2019-11-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cantidad_pizza',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='n_boleta',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='precio_final',
            field=models.IntegerField(),
        ),
    ]
