# Generated by Django 2.2.6 on 2019-11-17 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191117_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='n_boleta',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='precio_final',
        ),
    ]
